name: .NET Core

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Compile source (release configuration)
      run: dotnet build --configuration Release
    - name: Run unit tests (release configuration)
      run: dotnet test --configuration Release
